algorithm: moe
nEpochs: 1
gpu_mode: True
save_best: True
gpus: [0]
threads: 4 #num_works
log_dir: log/

seed: 123
checkpoint: ckpt/
data_dir_train: ../../multispectral_data/train 
data_dir_eval: ../../multispectral_data/eval

source_ms: ms
source_pan: pan

pretrain:
  pretrained: False
  pre_sr: ~
  pre_folder: ~

test:
  type: test # eval
  data_dir: ../../multispectral_data/test
  source_ms: ms
  source_pan: pan
  model: ~
  save_dir: pan-test/result/

data:
  upscale: 4
  batch_size: 32
  patch_size: 32
  data_augmentation: False
  n_colors: 4
  normalize: False

schedule:
  lr: 5e-4 #5e-6 1e-2
  optimizer: ADAM #ADAM, SGD, RMSprop
  beta1: 0.9 #ADAM beta1
  beta2: 0.999 #ADAM beta
  epsilon: 1e-8 #ADAM epsilon
  momentum: 0.9 #SGD momentum
  alpha: 0.9 #RMSprop alpha
  gclip: 4 #0.4 0.04
  loss: L1 # MSE, CE
  use_YCbCr: False
